# Generated by Django 4.2.30 on 2026-09-09 09:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_customer_accounts_receivable_customer_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=200)),
                ('frequency', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_invoice_date', models.DateField(blank=True, null=True)),
                ('last_invoice_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency', models.CharField(blank=True, default='INR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('active', 'ACTIVE'), ('stopped', 'STOPPED'), ('expired', 'EXPIRED')], default='active', max_length=20)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoices', to='customers.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='organizations.organization')),
            ],
            options={
                'db_table': 'recurring_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoiceActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('comment', 'Comment'), ('history', 'History')], default='history', max_length=20)),
                ('message', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_invoice_activities', to=settings.AUTH_USER_MODEL)),
                ('recurring_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='recurring_invoices.recurringinvoice')),
            ],
            options={
                'db_table': 'recurring_invoice_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
