# Generated by Django 4.2.30 on 2026-08-28 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0002_vendorpayment'),
        ('users', '0003_alter_user_email'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], default='goods', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('is_excise_product', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('synced_with_crm', models.BooleanField(default=False)),
                ('sales_enabled', models.BooleanField(default=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('sales_account', models.CharField(blank=True, default='Sales', max_length=100)),
                ('sales_description', models.TextField(blank=True)),
                ('tax', models.CharField(blank=True, max_length=100)),
                ('purchase_enabled', models.BooleanField(default=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('purchase_account', models.CharField(blank=True, default='Cost of Goods Sold', max_length=100)),
                ('purchase_description', models.TextField(blank=True)),
                ('track_inventory', models.BooleanField(default=False)),
                ('inventory_account', models.CharField(blank=True, default='Inventory Asset', max_length=100)),
                ('opening_stock', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('rate_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('valuation_method', models.CharField(blank=True, choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('wac', 'Weighted Average Cost')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to='users.user')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organizations.organization')),
                ('preferred_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_items', to='vendors.vendor')),
            ],
            options={
                'db_table': 'items',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('organization', 'sku'), name='unique_org_item_sku'),
        ),
    ]
