AUTO_LOCK_OPTIONS = (
    ("immediately", "Immediately"),
    ("seconds_30", "30 seconds"),
    ("minute_1", "1 minute"),
    ("minutes_5", "5 minutes"),
)

AUTO_LOCK_LABELS = dict(AUTO_LOCK_OPTIONS)

CONTACT_EMAIL = "sirajulhaq3154@gmail.com"
CONTACT_PHONE = "+91 96054 55758"
COMPANY_NAME = "Tech Geum Private Limited"
LAST_UPDATED = "August 2026"

TERMS_SECTIONS = (
    (
        "Acceptance of Terms",
        "By downloading, installing, or using Custom Books, you agree to be bound by these "
        "Terms of Service. If you do not agree to these terms, please do not use the application.",
    ),
    (
        "Description of Service",
        "Custom Books is an accounting and invoicing application designed for small businesses. "
        "The service includes features for managing customers, vendors, invoices, bills, expenses, "
        "inventory, and financial reporting.",
    ),
    (
        "User Responsibilities",
        "You are responsible for maintaining the accuracy of data entered into the application. "
        "You agree to use the service only for lawful purposes and in accordance with applicable "
        "accounting regulations in your jurisdiction.",
    ),
    (
        "Intellectual Property",
        "The Custom Books application, including its design, code, and content, is the intellectual "
        "property of Tech Geum Private Limited. You are granted a non-exclusive, non-transferable "
        "license to use the application for its intended purpose.",
    ),
    (
        "Data Ownership",
        "You retain full ownership of all financial data, customer information, and business records "
        "you enter into Custom Books. We do not claim any ownership rights over your data.",
    ),
    (
        "Limitation of Liability",
        'Custom Books is provided "as is" without warranties of any kind. Tech Geum Private Limited '
        "shall not be liable for any financial decisions made based on reports generated by the "
        "application. Always consult a qualified accountant for professional advice.",
    ),
    (
        "Termination",
        "You may stop using Custom Books at any time by uninstalling the application. We reserve the "
        "right to terminate or suspend access to the service for violations of these terms.",
    ),
    (
        "Changes to Terms",
        "We reserve the right to modify these Terms of Service at any time. Continued use of the "
        "application after changes constitutes acceptance of the new terms.",
    ),
    (
        "Contact",
        "For questions about these Terms of Service, contact us at:\n"
        f"Email: {CONTACT_EMAIL}\n"
        f"Phone: {CONTACT_PHONE}",
    ),
)

PRIVACY_SECTIONS = (
    (
        "Information We Collect",
        "Custom Books collects information you provide directly, including your name, email address, "
        "organization details, and financial data you enter into the application. This data is stored "
        "locally on your device and is not transmitted to external servers without your consent.",
    ),
    (
        "How We Use Your Information",
        "We use the information to provide and maintain the Custom Books service, including generating "
        "invoices, managing customer records, tracking expenses, and producing financial reports. Your "
        "data is used solely for the functionality of this application.",
    ),
    (
        "Data Storage & Security",
        "Your financial data is stored securely on your device using encrypted storage. We implement "
        "appropriate technical measures to protect your personal information against unauthorized access, "
        "alteration, or destruction.",
    ),
    (
        "Third-Party Services",
        "Custom Books may use third-party services for PDF generation, email delivery, and payment "
        "processing. These services have their own privacy policies, and we encourage you to review them. "
        "We do not sell your personal data to third parties.",
    ),
    (
        "Your Rights",
        "You have the right to access, update, or delete your personal information at any time through "
        "the application settings. You may also export your data or request a complete deletion of your "
        "account and associated data.",
    ),
    (
        "Changes to This Policy",
        "We may update this Privacy Policy from time to time. We will notify you of any changes by "
        "posting the new policy within the application. Changes are effective immediately upon posting.",
    ),
    (
        "Contact Us",
        "If you have any questions about this Privacy Policy, please contact us at:\n"
        f"Email: {CONTACT_EMAIL}\n"
        f"Phone: {CONTACT_PHONE}",
    ),
)
