# Generated by Django 4.2.30 on 2026-10-02 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPaymentGateway',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_code', models.CharField(max_length=30)),
                ('is_setup', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='organizations.organization')),
            ],
            options={
                'db_table': 'organization_payment_gateways',
                'ordering': ['gateway_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationpaymentgateway',
            constraint=models.UniqueConstraint(fields=('organization', 'gateway_code'), name='unique_organization_payment_gateway'),
        ),
    ]
