# Generated by Django 4.2.30 on 2026-09-14 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_customer_accounts_receivable_customer_currency_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('billing_method', models.CharField(choices=[('fixed_cost', 'Fixed Cost for Project'), ('project_hours', 'Based on Project Hours'), ('staff_hours', 'Based on Staff Hours'), ('task_hours', 'Based on Task Hours')], default='fixed_cost', max_length=30)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('budget_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(blank=True, default='INR', max_length=3)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('on_hold', 'ON HOLD'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('on_hold_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customers.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
