# Generated by Django 4.2.30 on 2026-10-01 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_vat_registered', models.BooleanField(default=False)),
                ('tax_registration_number', models.CharField(blank=True, max_length=20)),
                ('enable_international_trade', models.BooleanField(default=False)),
                ('vat_registration_date', models.DateField(blank=True, null=True)),
                ('first_tax_return_from', models.DateField(blank=True, null=True)),
                ('reporting_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('profit_margin_scheme', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_settings', to='organizations.organization')),
            ],
            options={
                'db_table': 'tax_settings',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tax_type', models.CharField(choices=[('tax', 'Tax'), ('group', 'Tax Group')], default='tax', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='taxes.taxrate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='organizations.organization')),
            ],
            options={
                'db_table': 'tax_rates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_organization_tax_name'),
        ),
    ]
