# Generated by Django 4.2.30 on 2026-07-16 06:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('customers', '0002_customeraddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=30)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('payment_mode_id', models.UUIDField(blank=True, null=True)),
                ('bank_account_id', models.UUIDField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='organizations.organization')),
            ],
            options={
                'db_table': 'customer_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customerpayment',
            constraint=models.UniqueConstraint(fields=('organization', 'payment_number'), name='unique_org_payment_number'),
        ),
    ]
