# Generated by Django 4.2.30 on 2026-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='portal_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='receivables',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='customer',
            name='synced_with_crm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='unused_credits',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
    ]
