# Generated by Django 4.2.30 on 2026-09-01 17:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_is_overdue_customer_portal_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accounts_receivable',
            field=models.CharField(blank=True, default='accounts_receivable', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('individual', 'Individual')], default='business', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_country_code',
            field=models.CharField(blank=True, default='+91', max_length=8),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, default='due_on_receipt', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_country_code',
            field=models.CharField(blank=True, default='+91', max_length=8),
        ),
        migrations.AddField(
            model_name='customer',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='portal_language',
            field=models.CharField(blank=True, default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='customer',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='salutation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_treatment',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CustomerSocialLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(blank=True, choices=[('website', 'Website'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('other', 'Other')], default='website', max_length=20)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='customers.customer')),
            ],
            options={
                'db_table': 'customer_social_links',
                'ordering': ['platform', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContactPerson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salutation', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('work_phone_country_code', models.CharField(blank=True, default='+91', max_length=8)),
                ('work_phone', models.CharField(blank=True, max_length=20)),
                ('mobile_country_code', models.CharField(blank=True, default='+91', max_length=8)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='customers.customer')),
            ],
            options={
                'db_table': 'customer_contact_persons',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
