# Generated by Django 4.2.30 on 2026-09-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_password_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
