# Generated by Django 4.2.30 on 2026-10-03 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySecurity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_app_lock', models.BooleanField(default=False)),
                ('biometric_unlock', models.BooleanField(default=True)),
                ('lock_on_app_exit', models.BooleanField(default=True)),
                ('auto_lock_after', models.CharField(choices=[('immediately', 'Immediately'), ('seconds_30', '30 seconds'), ('minute_1', '1 minute'), ('minutes_5', '5 minutes')], default='immediately', max_length=20)),
                ('hide_amounts_on_dashboard', models.BooleanField(default=True)),
                ('cache_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_security', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'privacy_security',
            },
        ),
    ]
