# Generated by Django 4.2.30 on 2026-10-03 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadResolution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution', models.CharField(choices=[('high', 'high'), ('low', 'low'), ('original', 'original'), ('medium', 'medium')], default='medium', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_upload_resolution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image_upload_resolutions',
            },
        ),
    ]
