# Generated by Django 4.2.30 on 2026-07-16 08:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('storage_key', models.TextField(blank=True)),
                ('attachable_type', models.CharField(blank=True, max_length=50)),
                ('attachable_id', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='organizations.organization')),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['attachable_type', 'attachable_id'], name='attachments_attacha_89ec86_idx')],
            },
        ),
    ]
