# Generated by Django 4.2.30 on 2026-10-02 15:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderEmailPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('system', 'Techgeum Email Address'), ('sender', "Sender's Email Address")], default='system', max_length=20)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender_email_preference', to='organizations.organization')),
            ],
            options={
                'db_table': 'sender_email_preferences',
            },
        ),
        migrations.CreateModel(
            name='SenderEmail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_emails', to='organizations.organization')),
            ],
            options={
                'db_table': 'sender_emails',
                'ordering': ['-is_primary', 'name', 'email'],
            },
        ),
        migrations.AddConstraint(
            model_name='senderemail',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='unique_organization_sender_email'),
        ),
    ]
