# Generated by Django 4.2.30 on 2026-09-15 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('storage_key', models.TextField(blank=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('spreadsheet', 'Spreadsheet'), ('document', 'Document')], default='document', max_length=20)),
                ('folder', models.CharField(default='Inbox', max_length=50)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_documents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_documents', to='organizations.organization')),
            ],
            options={
                'db_table': 'inbox_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
