import io
from datetime import datetime


PAGE_SIZES = {
    "A4": (595.28, 841.89),
    "letter": (612.0, 792.0),
    "legal": (612.0, 1008.0),
}


def _escape(text):
    return (
        str(text or "")
        .replace("\\", "\\\\")
        .replace("(", "\\(")
        .replace(")", "\\)")
        .replace("\r", " ")
        .replace("\n", " ")
    )


def _to_points(value, default):
    try:
        return float(value) * 72
    except (TypeError, ValueError):
        return default


def build_financial_pdf(report, export_options, generated_by=""):
    options = export_options or {}
    display = options.get("display") or {}
    paper = (options.get("paper_size") or "A4").lower()
    width, height = PAGE_SIZES.get(paper, PAGE_SIZES["A4"])
    orientation = (options.get("orientation") or "portrait").lower()
    if orientation == "landscape":
        width, height = height, width
    margins = options.get("margins") or {}
    top = _to_points(margins.get("top"), 0.7 * 72)
    bottom = _to_points(margins.get("bottom"), 0.55 * 72)
    left = _to_points(margins.get("left"), 0.2 * 72)
    right = _to_points(margins.get("right"), 0.2 * 72)
    density = (options.get("table_density") or "classic").lower()
    if density == "compact":
        font_size, line_height = 9, 12
    elif density == "comfortable":
        font_size, line_height = 13, 20
    else:
        font_size, line_height = 11, 16
    header_each_page = bool(options.get("column_headers_on_each_page", True))
    language = (options.get("language") or "en").lower()
    now = datetime.now()
    title = report.get("title") or "Report"
    if language == "ar":
        title_map = {
            "Balance Sheet": "Balance Sheet",
            "Profit and Loss": "Profit and Loss",
            "Cash Flow Statement": "Cash Flow Statement",
            "Sales by Customer": "Sales by Customer",
            "Sales by Item": "Sales by Item",
            "Sales by Sales Person": "Sales by Sales Person",
            "Customer Balance Summary": "Customer Balance Summary",
            "AR Aging Summary": "AR Aging Summary",
            "AR Aging Details": "AR Aging Details",
        }
        title = title_map.get(title, title)

    header_lines = []
    if display.get("organization_name", True):
        header_lines.append(("center", 14, report.get("organization_name") or ""))
    header_lines.append(("center", 16, title))
    if display.get("report_basis", True) and report.get("basis_label"):
        header_lines.append(("center", 10, report.get("basis_label")))
    if report.get("as_of_display"):
        header_lines.append(("center", 10, report.get("as_of_display")))
    elif report.get("period_display"):
        header_lines.append(("center", 10, report.get("period_display")))
    if display.get("organization_details"):
        details = report.get("organization_details") or {}
        detail_text = ", ".join(
            part for part in (details.get("state"), details.get("country"), details.get("currency")) if part
        )
        if detail_text:
            header_lines.append(("center", 9, detail_text))

    meta_lines = []
    if display.get("generated_by") and generated_by:
        meta_lines.append(f"Generated By: {generated_by}")
    if display.get("generated_date"):
        meta_lines.append(f"Generated Date: {now.strftime('%d %b %Y')}")
    if display.get("generated_time"):
        meta_lines.append(f"Generated Time: {now.strftime('%H:%M')}")

    columns = report.get("columns") or [
        {"key": "account", "label": "ACCOUNT"},
        {"key": "total", "label": "TOTAL"},
    ]
    is_table = bool(columns) and columns[0].get("key") not in ("account",)
    has_compare = any(col.get("key") == "compare" for col in columns)
    amount_width = 90
    compare_width = 90 if has_compare else 0
    table_right = width - right
    usable = table_right - left
    col_count = max(len(columns), 1)
    col_width = usable / col_count

    def header_commands(page_top):
        commands = ["BT"]
        y = page_top
        for align, size, text in header_lines:
            y -= size + 4
            commands.append(f"/F1 {size} Tf")
            commands.append(f"1 0 0 1 {left:.2f} {y:.2f} Tm")
            commands.append(f"({_escape(text)}) Tj")
        y -= 10
        commands.append(f"/F1 {font_size} Tf")
        if is_table:
            for index, column in enumerate(columns):
                x = left + (index * col_width)
                commands.append(f"1 0 0 1 {x:.2f} {y:.2f} Tm")
                commands.append(f"({_escape(column.get('label', ''))}) Tj")
        else:
            commands.append(f"1 0 0 1 {left:.2f} {y:.2f} Tm")
            commands.append(f"({_escape(columns[0].get('label', 'ACCOUNT'))}) Tj")
            commands.append(
                f"1 0 0 1 {table_right - amount_width - compare_width:.2f} {y:.2f} Tm"
            )
            commands.append(
                f"({_escape(columns[1].get('label', 'TOTAL') if len(columns) > 1 else 'TOTAL')}) Tj"
            )
            if has_compare:
                commands.append(f"1 0 0 1 {table_right - compare_width:.2f} {y:.2f} Tm")
                commands.append(f"({_escape(columns[2].get('label', ''))}) Tj")
        commands.append("ET")
        y -= 8
        return commands, y

    rows = report.get("rows") or []
    pages = []
    page_number = 1
    commands, y = header_commands(height - top)
    if report.get("empty") and report.get("empty_message"):
        commands.append("BT")
        commands.append(f"/F1 {font_size} Tf")
        commands.append(f"1 0 0 1 {left:.2f} {y:.2f} Tm")
        commands.append(f"({_escape(report.get('empty_message'))}) Tj")
        commands.append("ET")
        y -= line_height
    for row in rows:
        if y < bottom + 60:
            pages.append((page_number, commands))
            page_number += 1
            commands, y = header_commands(height - top) if header_each_page else ([], height - top)
            if not header_each_page:
                commands = ["BT", "ET"]
        commands.append("BT")
        if is_table:
            commands.append(f"/F1 {font_size} Tf")
            for index, column in enumerate(columns):
                key = column.get("key")
                value = row.get(f"{key}_display") or row.get(key) or ""
                x = left + (index * col_width)
                commands.append(f"1 0 0 1 {x:.2f} {y:.2f} Tm")
                commands.append(f"({_escape(value)}) Tj")
        else:
            indent = int(row.get("depth") or 0) * 12
            label = row.get("label") or ""
            if len(label) > 70:
                label = label[:67] + "..."
            amount = row.get("amount_display") or row.get("amount") or ""
            compare = row.get("compare_amount_display") or row.get("compare_amount") or ""
            size = font_size + (1 if row.get("row_type") in ("section", "total") else 0)
            commands.append(f"/F1 {size} Tf")
            commands.append(f"1 0 0 1 {left + indent:.2f} {y:.2f} Tm")
            commands.append(f"({_escape(label)}) Tj")
            commands.append(
                f"1 0 0 1 {table_right - amount_width - compare_width:.2f} {y:.2f} Tm"
            )
            commands.append(f"({_escape(amount)}) Tj")
            if has_compare:
                commands.append(f"1 0 0 1 {table_right - compare_width:.2f} {y:.2f} Tm")
                commands.append(f"({_escape(compare)}) Tj")
        commands.append("ET")
        y -= line_height

    note = (options.get("temporary_note") or "").strip()
    footer_bits = list(meta_lines)
    if report.get("currency_note"):
        symbol = report.get("currency_symbol") or ""
        footer_bits.append(f"{report['currency_note']} {symbol}".strip())
    if note:
        footer_bits.append(note)
    if y < bottom + 40:
        pages.append((page_number, commands))
        page_number += 1
        commands, y = header_commands(height - top) if header_each_page else ([], height - top)
    for text in footer_bits:
        commands.append("BT")
        commands.append(f"/F1 8 Tf")
        commands.append(f"1 0 0 1 {left:.2f} {y:.2f} Tm")
        commands.append(f"({_escape(text)}) Tj")
        commands.append("ET")
        y -= 11
    pages.append((page_number, commands))

    font_obj = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
    content_streams = []
    for number, page_commands in pages:
        stream = "\n".join(page_commands)
        if display.get("page_number"):
            stream += (
                f"\nBT\n/F1 8 Tf\n1 0 0 1 {width / 2:.2f} {bottom / 2:.2f} Tm\n"
                f"({number}) Tj\nET"
            )
        content_streams.append(stream)

    pdf = io.BytesIO()
    offsets = [0]

    def write_obj(content):
        offsets.append(pdf.tell())
        obj_number = len(offsets) - 1
        pdf.write(f"{obj_number} 0 obj\n".encode("latin-1"))
        if isinstance(content, bytes):
            pdf.write(content)
            if not content.endswith(b"\n"):
                pdf.write(b"\n")
        else:
            pdf.write(f"{content}\n".encode("latin-1", "replace"))
        pdf.write(b"endobj\n")
        return obj_number

    pdf.write(b"%PDF-1.4\n")
    write_obj("<< /Type /Catalog /Pages 2 0 R >>")
    total_pages = len(pages)
    kids = " ".join(f"{4 + i * 2} 0 R" for i in range(total_pages))
    write_obj(f"<< /Type /Pages /Kids [{kids}] /Count {total_pages} >>")
    write_obj(font_obj)
    for stream in content_streams:
        page_id = len(offsets)
        content_id = page_id + 1
        write_obj(
            "<< /Type /Page /Parent 2 0 R "
            f"/MediaBox [0 0 {width:.2f} {height:.2f}] "
            f"/Contents {content_id} 0 R "
            "/Resources << /Font << /F1 3 0 R >> >> >>"
        )
        payload = stream.encode("latin-1", "replace")
        write_obj(b"<< /Length %d >>\nstream\n" % len(payload) + payload + b"\nendstream")

    xref_pos = pdf.tell()
    pdf.write(f"xref\n0 {len(offsets)}\n".encode("latin-1"))
    pdf.write(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf.write(f"{offset:010d} 00000 n \n".encode("latin-1"))
    pdf.write(
        f"trailer << /Size {len(offsets)} /Root 1 0 R >>\nstartxref\n{xref_pos}\n%%EOF\n".encode(
            "latin-1"
        )
    )
    return pdf.getvalue()
