from django.urls import path

from apps.reports.financial_views import (
    BalanceSheetExportFormView,
    BalanceSheetExportView,
    BalanceSheetFormView,
    BalanceSheetOptionsView,
    BalanceSheetView,
    CashFlowStatementExportFormView,
    CashFlowStatementExportView,
    CashFlowStatementFormView,
    CashFlowStatementOptionsView,
    CashFlowStatementView,
    FinancialReportIndexView,
    FinancialReportOptionsView,
    ProfitAndLossExportFormView,
    ProfitAndLossExportView,
    ProfitAndLossFormView,
    ProfitAndLossOptionsView,
    ProfitAndLossView,
)
from apps.reports.sales_views import (
    SalesByCustomerExportFormView,
    SalesByCustomerExportView,
    SalesByCustomerFormView,
    SalesByCustomerOptionsView,
    SalesByCustomerView,
    SalesByItemExportFormView,
    SalesByItemExportView,
    SalesByItemFormView,
    SalesByItemOptionsView,
    SalesByItemView,
    SalesBySalesPersonExportFormView,
    SalesBySalesPersonExportView,
    SalesBySalesPersonFormView,
    SalesBySalesPersonOptionsView,
    SalesBySalesPersonView,
    SalesReportIndexView,
    SalesReportOptionsView,
)
from apps.reports.views import ReportFormView, ReportOptionsView, ReportView

urlpatterns = [
    path("", ReportView.as_view(), name="reports"),
    path("options/", ReportOptionsView.as_view(), name="reports-options"),
    path("form/", ReportFormView.as_view(), name="reports-form"),
    path("financial/", FinancialReportIndexView.as_view(), name="financial-reports"),
    path(
        "financial/options/",
        FinancialReportOptionsView.as_view(),
        name="financial-reports-options",
    ),
    path(
        "financial/balance-sheet/",
        BalanceSheetView.as_view(),
        name="financial-balance-sheet",
    ),
    path(
        "financial/balance-sheet/options/",
        BalanceSheetOptionsView.as_view(),
        name="financial-balance-sheet-options",
    ),
    path(
        "financial/balance-sheet/form/",
        BalanceSheetFormView.as_view(),
        name="financial-balance-sheet-form",
    ),
    path(
        "financial/balance-sheet/run/",
        BalanceSheetView.as_view(),
        name="financial-balance-sheet-run",
    ),
    path(
        "financial/balance-sheet/export-form/",
        BalanceSheetExportFormView.as_view(),
        name="financial-balance-sheet-export-form",
    ),
    path(
        "financial/balance-sheet/export/",
        BalanceSheetExportView.as_view(),
        name="financial-balance-sheet-export",
    ),
    path(
        "financial/profit-and-loss/",
        ProfitAndLossView.as_view(),
        name="financial-profit-and-loss",
    ),
    path(
        "financial/profit-and-loss/options/",
        ProfitAndLossOptionsView.as_view(),
        name="financial-profit-and-loss-options",
    ),
    path(
        "financial/profit-and-loss/form/",
        ProfitAndLossFormView.as_view(),
        name="financial-profit-and-loss-form",
    ),
    path(
        "financial/profit-and-loss/run/",
        ProfitAndLossView.as_view(),
        name="financial-profit-and-loss-run",
    ),
    path(
        "financial/profit-and-loss/export-form/",
        ProfitAndLossExportFormView.as_view(),
        name="financial-profit-and-loss-export-form",
    ),
    path(
        "financial/profit-and-loss/export/",
        ProfitAndLossExportView.as_view(),
        name="financial-profit-and-loss-export",
    ),
    path(
        "financial/cash-flow-statement/",
        CashFlowStatementView.as_view(),
        name="financial-cash-flow",
    ),
    path(
        "financial/cash-flow-statement/options/",
        CashFlowStatementOptionsView.as_view(),
        name="financial-cash-flow-options",
    ),
    path(
        "financial/cash-flow-statement/form/",
        CashFlowStatementFormView.as_view(),
        name="financial-cash-flow-form",
    ),
    path(
        "financial/cash-flow-statement/run/",
        CashFlowStatementView.as_view(),
        name="financial-cash-flow-run",
    ),
    path(
        "financial/cash-flow-statement/export-form/",
        CashFlowStatementExportFormView.as_view(),
        name="financial-cash-flow-export-form",
    ),
    path(
        "financial/cash-flow-statement/export/",
        CashFlowStatementExportView.as_view(),
        name="financial-cash-flow-export",
    ),
    path("sales/", SalesReportIndexView.as_view(), name="sales-reports"),
    path(
        "sales/options/",
        SalesReportOptionsView.as_view(),
        name="sales-reports-options",
    ),
    path(
        "sales/sales-by-customer/",
        SalesByCustomerView.as_view(),
        name="sales-by-customer",
    ),
    path(
        "sales/sales-by-customer/options/",
        SalesByCustomerOptionsView.as_view(),
        name="sales-by-customer-options",
    ),
    path(
        "sales/sales-by-customer/form/",
        SalesByCustomerFormView.as_view(),
        name="sales-by-customer-form",
    ),
    path(
        "sales/sales-by-customer/run/",
        SalesByCustomerView.as_view(),
        name="sales-by-customer-run",
    ),
    path(
        "sales/sales-by-customer/export-form/",
        SalesByCustomerExportFormView.as_view(),
        name="sales-by-customer-export-form",
    ),
    path(
        "sales/sales-by-customer/export/",
        SalesByCustomerExportView.as_view(),
        name="sales-by-customer-export",
    ),
    path(
        "sales/sales-by-item/",
        SalesByItemView.as_view(),
        name="sales-by-item",
    ),
    path(
        "sales/sales-by-item/options/",
        SalesByItemOptionsView.as_view(),
        name="sales-by-item-options",
    ),
    path(
        "sales/sales-by-item/form/",
        SalesByItemFormView.as_view(),
        name="sales-by-item-form",
    ),
    path(
        "sales/sales-by-item/run/",
        SalesByItemView.as_view(),
        name="sales-by-item-run",
    ),
    path(
        "sales/sales-by-item/export-form/",
        SalesByItemExportFormView.as_view(),
        name="sales-by-item-export-form",
    ),
    path(
        "sales/sales-by-item/export/",
        SalesByItemExportView.as_view(),
        name="sales-by-item-export",
    ),
    path(
        "sales/sales-by-sales-person/",
        SalesBySalesPersonView.as_view(),
        name="sales-by-sales-person",
    ),
    path(
        "sales/sales-by-sales-person/options/",
        SalesBySalesPersonOptionsView.as_view(),
        name="sales-by-sales-person-options",
    ),
    path(
        "sales/sales-by-sales-person/form/",
        SalesBySalesPersonFormView.as_view(),
        name="sales-by-sales-person-form",
    ),
    path(
        "sales/sales-by-sales-person/run/",
        SalesBySalesPersonView.as_view(),
        name="sales-by-sales-person-run",
    ),
    path(
        "sales/sales-by-sales-person/export-form/",
        SalesBySalesPersonExportFormView.as_view(),
        name="sales-by-sales-person-export-form",
    ),
    path(
        "sales/sales-by-sales-person/export/",
        SalesBySalesPersonExportView.as_view(),
        name="sales-by-sales-person-export",
    ),
]
