# Generated by Django 4.2.30 on 2026-10-01 20:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoices', 'Invoices Template'), ('quotes', 'Quotes Template'), ('sales_orders', 'Sales Orders Template'), ('purchase_orders', 'Purchase Orders Template'), ('credit_notes', 'Credit Notes Template'), ('delivery_challans', 'Delivery Challans Template')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('theme', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('red', 'Red'), ('purple', 'Purple'), ('orange', 'Orange')], default='blue', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('ifsc_swift_code', models.CharField(blank=True, max_length=20)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('signatory_name', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_templates', to='organizations.organization')),
            ],
            options={
                'db_table': 'pdf_templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='pdftemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'document_type', 'name'), name='unique_pdf_template_name'),
        ),
    ]
