# Generated by Django 4.2.30 on 2026-09-07 18:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_customer_accounts_receivable_customer_currency_and_more'),
        ('items', '0001_initial'),
        ('delivery_challans', '0001_initial'),
        ('sales_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=30)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, default='due_on_receipt', max_length=40)),
                ('place_of_supply', models.CharField(blank=True, max_length=100)),
                ('tax_treatment', models.CharField(blank=True, max_length=40)),
                ('salesperson_id', models.UUIDField(blank=True, null=True)),
                ('salesperson_name', models.CharField(blank=True, max_length=200)),
                ('subject', models.TextField(blank=True)),
                ('tax_type', models.CharField(blank=True, choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=20)),
                ('customer_notes', models.TextField(blank=True, default='Thanks for your business.')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('email_recipients', models.JSONField(blank=True, default=list)),
                ('payment_received', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('sent', 'SENT'), ('paid', 'PAID'), ('partially_paid', 'PARTIALLY PAID'), ('cancelled', 'CANCELLED')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency', models.CharField(blank=True, default='INR', max_length=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
                ('delivery_challan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='delivery_challans.deliverychallan')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales_orders.salesorder')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=19)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='items.item')),
            ],
            options={
                'db_table': 'invoice_lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'invoice_number'), name='unique_org_invoice_number'),
        ),
    ]
