# Generated by Django 4.2.30 on 2026-09-08 10:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('invoices', '0001_initial'),
        ('customers', '0005_customer_accounts_receivable_customer_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceived',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=30)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='bank_transfer', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('amount_applied', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency', models.CharField(blank=True, default='INR', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('bank_account_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments_received', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='customers.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='organizations.organization')),
            ],
            options={
                'db_table': 'payments_received',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceivedApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_applications', to='invoices.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='payments_received.paymentreceived')),
            ],
            options={
                'db_table': 'payment_received_applications',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentreceivedapplication',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_payment_invoice_application'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceived',
            constraint=models.UniqueConstraint(fields=('organization', 'payment_number'), name='unique_org_payment_received_number'),
        ),
    ]
