# Generated by Django 4.2.30 on 2026-09-29 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments_received', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceived',
            name='bank_charges',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='template',
            field=models.CharField(choices=[('standard', 'Standard Template'), ('elite', 'Elite Template'), ('classic', 'Classic Template')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentreceived',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('credit_card', 'Credit Card'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='bank_transfer', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentReceivedActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('comment', 'Comment'), ('history', 'History')], default='history', max_length=20)),
                ('message', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_received_activities', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='payments_received.paymentreceived')),
            ],
            options={
                'db_table': 'payment_received_activities',
                'ordering': ['created_at'],
            },
        ),
    ]
