# Generated by Django 4.2.30 on 2026-09-15 10:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualJournal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_number', models.CharField(max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('journal_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency', models.CharField(blank=True, default='INR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('published', 'PUBLISHED')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manual_journals', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_journals', to='organizations.organization')),
            ],
            options={
                'db_table': 'manual_journals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='manualjournal',
            constraint=models.UniqueConstraint(fields=('organization', 'journal_number'), name='unique_org_manual_journal_number'),
        ),
    ]
