# Generated by Django 4.2.30 on 2026-10-02 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningScreen',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screen', models.CharField(choices=[('home', 'Home'), ('customers', 'Customers'), ('invoices', 'Invoices'), ('items', 'Items'), ('quotes', 'Quotes'), ('sales_orders', 'Sales Orders'), ('vendors', 'Vendors'), ('bills', 'Bills'), ('reports', 'Reports'), ('settings', 'Settings')], default='home', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening_screen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opening_screens',
            },
        ),
    ]
