# Generated by Django 4.2.30 on 2026-09-30 12:44

import apps.preferences.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled_modules', models.JSONField(blank=True, default=apps.preferences.models.default_enabled_modules)),
                ('attach_pdf_in_email', models.BooleanField(default=True)),
                ('encrypt_pdf', models.BooleanField(default=False)),
                ('discount_type', models.CharField(choices=[('none', "I don't give discounts"), ('line_item', 'At Line Item Level'), ('invoice', 'At Invoice Level')], default='line_item', max_length=20)),
                ('tax_type', models.CharField(choices=[('tax_inclusive', 'Tax Inclusive'), ('tax_exclusive', 'Tax Exclusive'), ('both', 'Tax Inclusive or Tax Exclusive')], default='both', max_length=20)),
                ('rounding', models.CharField(choices=[('none', 'No Rounding'), ('nearest_whole', 'Round off the total to the nearest whole number')], default='none', max_length=20)),
                ('enable_salesperson_field', models.BooleanField(default=True)),
                ('organization_address_format', models.TextField(blank=True, default='${ORGANIZATION.NAME}\n${ORGANIZATION.STREET_ADDRESS}\n${ORGANIZATION.CITY} ${ORGANIZATION.STATE}\n${ORGANIZATION.POSTAL_CODE}\n${ORGANIZATION.COUNTRY}\n${ORGANIZATION.TRN_LABEL} ${ORGANIZATION.TRN_VALUE}\n${ORGANIZATION.PHONE}\n${ORGANIZATION.EMAIL}\n${ORGANIZATION.WEBSITE}')),
                ('default_customer_type', models.CharField(choices=[('business', 'Business'), ('individual', 'Individual')], default='business', max_length=20)),
                ('allow_duplicate_display_name', models.BooleanField(default=True)),
                ('enable_credit_limit', models.BooleanField(default=False)),
                ('billing_address_format', models.TextField(blank=True, default='${CONTACT.CONTACT_DISPLAYNAME}\n${CONTACT.CONTACT_ADDRESS}\n${CONTACT.CONTACT_CITY}\n${CONTACT.CONTACT_CODE} ${CONTACT.CONTACT_STATE}\n${CONTACT.CONTACT_COUNTRY}\n${CONTACT.TRN_LABEL} ${CONTACT.TRN}')),
                ('shipping_address_format', models.TextField(blank=True, default='${CONTACT.CONTACT_ADDRESS}\n${CONTACT.CONTACT_CITY}\n${CONTACT.CONTACT_CODE} ${CONTACT.CONTACT_STATE}\n${CONTACT.CONTACT_COUNTRY}\n${CONTACT.TRN_LABEL} ${CONTACT.TRN}')),
                ('enable_inventory', models.BooleanField(default=False)),
                ('inventory_start_date', models.DateField(blank=True, null=True)),
                ('notify_below_reorder_point', models.BooleanField(default=False)),
                ('quote_auto_generate_number', models.BooleanField(default=True)),
                ('quote_prefix', models.CharField(blank=True, default='QT-', max_length=20)),
                ('quote_next_number', models.PositiveIntegerField(default=1)),
                ('quote_notes', models.TextField(blank=True, default='Looking forward for your business.')),
                ('quote_terms', models.TextField(blank=True)),
                ('quote_auto_convert_to_invoice', models.BooleanField(default=False)),
                ('quote_prefill_country_code', models.BooleanField(default=False)),
                ('quote_default_country_code', models.CharField(blank=True, max_length=8)),
                ('invoice_auto_generate_number', models.BooleanField(default=True)),
                ('invoice_prefix', models.CharField(blank=True, default='INV-', max_length=20)),
                ('invoice_next_number', models.PositiveIntegerField(default=1)),
                ('invoice_notes', models.TextField(blank=True, default='Thanks for your business.')),
                ('invoice_terms', models.TextField(blank=True)),
                ('invoice_allow_edit_sent', models.BooleanField(default=True)),
                ('invoice_discount_before_tax', models.BooleanField(default=True)),
                ('invoice_show_expense_receipts_in_pdf', models.BooleanField(default=False)),
                ('mileage_unit', models.CharField(choices=[('kilometer', 'Kilometer'), ('mile', 'Mile')], default='kilometer', max_length=20)),
                ('mileage_category', models.CharField(choices=[('fuel_mileage', 'Fuel/Mileage Expenses'), ('travel', 'Travel Expenses'), ('vehicle', 'Vehicle Expenses')], default='fuel_mileage', max_length=20)),
                ('vendor_portal_notify_activity', models.BooleanField(default=True)),
                ('vendor_portal_notify_vendors_on_comment', models.BooleanField(default=True)),
                ('vendor_portal_allow_contact_update', models.BooleanField(default=False)),
                ('vendor_portal_allow_po_accept_reject', models.BooleanField(default=False)),
                ('vendor_portal_allow_document_upload', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='organizations.organization')),
            ],
            options={
                'db_table': 'preferences',
            },
        ),
        migrations.CreateModel(
            name='MileageRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_rates', to='organizations.organization')),
            ],
            options={
                'db_table': 'preference_mileage_rates',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(choices=[('customers_vendors', 'Customers And Vendors'), ('items', 'Items'), ('quotes', 'Quotes'), ('invoices', 'Invoices'), ('credit_notes', 'Credit Notes'), ('sales_orders', 'Sales Orders'), ('expenses', 'Expenses'), ('bills', 'Bills'), ('purchase_orders', 'Purchase Orders')], max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('multiline', 'Multi-line Text'), ('email', 'Email'), ('url', 'URL'), ('phone', 'Phone'), ('number', 'Number'), ('decimal', 'Decimal'), ('amount', 'Amount'), ('percent', 'Percent'), ('date', 'Date'), ('checkbox', 'Check Box'), ('dropdown', 'Dropdown')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('show_in_pdf', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='organizations.organization')),
            ],
            options={
                'db_table': 'preference_custom_fields',
                'ordering': ['entity', 'sort_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mileagerate',
            constraint=models.UniqueConstraint(fields=('organization', 'start_date'), name='unique_mileage_rate_start_date'),
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.UniqueConstraint(fields=('organization', 'entity', 'label'), name='unique_custom_field_label_per_entity'),
        ),
    ]
