# Generated by Django 4.2.30 on 2026-07-12 17:59

import django.contrib.postgres.fields.citext
import uuid
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', django.contrib.postgres.fields.citext.CITextField(unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['email'],
            },
        ),
    ]
