# Generated by Django 4.2.30 on 2026-08-28 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('quantity', 'By Quantity'), ('value', 'By Value')], default='quantity', max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('completed', 'COMPLETED')], default='draft', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('account', models.CharField(blank=True, default='Inventory Asset', max_length=100)),
                ('adjusted_by_name', models.CharField(blank=True, max_length=200)),
                ('quantity_change', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('adjustment_value', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('stock_applied', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='organizations.organization')),
            ],
            options={
                'db_table': 'inventory_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_adjusted', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryadjustment')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustment_lines', to='items.item')),
            ],
            options={
                'db_table': 'inventory_adjustment_lines',
                'ordering': ['id'],
            },
        ),
    ]
