# Generated by Django 4.2.30 on 2026-09-25 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustmentActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('comment', 'Comment'), ('history', 'History')], default='history', max_length=20)),
                ('message', models.TextField()),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='inventory.inventoryadjustment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustment_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_adjustment_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
