# Generated by Django 4.2.30 on 2026-09-14 08:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('vendors', '0003_vendor_contact_and_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCredit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('credit_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency', models.CharField(blank=True, default='INR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('open', 'OPEN'), ('closed', 'CLOSED'), ('void', 'VOID')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_credits', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_credits', to='organizations.organization')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_credits', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_credits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='vendorcredit',
            constraint=models.UniqueConstraint(fields=('organization', 'credit_note_number'), name='unique_org_vendor_credit_number'),
        ),
    ]
