# Generated by Django 4.2.30 on 2026-09-02 17:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_customer_accounts_receivable_customer_currency_and_more'),
        ('items', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('quote_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('salesperson_id', models.UUIDField(blank=True, null=True)),
                ('salesperson_name', models.CharField(blank=True, max_length=200)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('tax_type', models.CharField(blank=True, choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=20)),
                ('customer_notes', models.TextField(blank=True, default='Looking forward for your business.')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('sent', 'SENT'), ('accepted', 'ACCEPTED'), ('declined', 'DECLINED'), ('expired', 'EXPIRED'), ('converted', 'CONVERTED')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency', models.CharField(blank=True, default='INR', max_length=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='organizations.organization')),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=19)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='items.item')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quote')),
            ],
            options={
                'db_table': 'quote_lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('organization', 'quote_number'), name='unique_org_quote_number'),
        ),
    ]
