# Generated by Django 4.2.30 on 2026-07-13 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=100)),
                ('permission_level', models.CharField(choices=[('none', 'None'), ('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('full', 'Full')], max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='roles.role')),
            ],
            options={
                'db_table': 'role_permissions',
                'ordering': ['module'],
            },
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'module'), name='unique_role_module_permission'),
        ),
    ]
