# Generated by Django 4.2.30 on 2026-09-07 09:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quotes", "0001_initial"),
        ("customers", "0005_customer_accounts_receivable_customer_currency_and_more"),
        ("items", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sales_order_number", models.CharField(max_length=30)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("order_date", models.DateField(default=datetime.date.today)),
                ("expected_shipment_date", models.DateField(blank=True, null=True)),
                ("payment_terms", models.CharField(blank=True, max_length=40)),
                ("delivery_method", models.CharField(blank=True, max_length=100)),
                ("salesperson_id", models.UUIDField(blank=True, null=True)),
                ("salesperson_name", models.CharField(blank=True, max_length=200)),
                ("project_id", models.UUIDField(blank=True, null=True)),
                ("project_name", models.CharField(blank=True, max_length=200)),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "tax_type",
                    models.CharField(
                        blank=True,
                        choices=[("exclusive", "Exclusive"), ("inclusive", "Inclusive")],
                        default="exclusive",
                        max_length=20,
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(
                        blank=True, default="Looking forward for your business."
                    ),
                ),
                ("terms_and_conditions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "DRAFT"),
                            ("confirmed", "CONFIRMED"),
                            ("invoiced", "INVOICED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("invoiced_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("currency", models.CharField(blank=True, default="INR", max_length=3)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sales_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_orders",
                        to="organizations.organization",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_orders",
                        to="quotes.quote",
                    ),
                ),
            ],
            options={
                "db_table": "sales_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=19),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("tax", models.CharField(blank=True, max_length=100)),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_order_lines",
                        to="items.item",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales_orders.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "sales_order_lines",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="salesorder",
            constraint=models.UniqueConstraint(
                fields=("organization", "sales_order_number"),
                name="unique_org_sales_order_number",
            ),
        ),
    ]
