# Generated by Django 4.2.30 on 2026-09-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='attention',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='address',
            name='fax',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_country_code',
            field=models.CharField(blank=True, default='+91', max_length=8),
        ),
    ]
