# Generated by Django 4.2.30 on 2026-08-31 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('undeposited_funds', 'Undeposited Funds')], default='bank', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('account_code', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('books_balance', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('bank_balance', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organizations.organization')),
            ],
            options={
                'db_table': 'bank_accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='organizations.organization')),
            ],
            options={
                'db_table': 'bank_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_bank_account_name'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_code', ''), _negated=True), fields=('organization', 'account_code'), name='unique_org_bank_account_code'),
        ),
    ]
