# Generated by Django 4.2.30 on 2026-07-10 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, choices=[('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('it_software', 'IT / Software'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('consulting', 'Consulting'), ('hospitality', 'Hospitality'), ('real_estate', 'Real Estate'), ('transportation', 'Transportation'), ('agriculture', 'Agriculture'), ('finance', 'Finance'), ('other', 'Other')], max_length=30)),
                ('country', models.CharField(max_length=2)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('is_gst_registered', models.BooleanField(default=False)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_setup_complete', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
