# Generated by Django 4.2.30 on 2026-09-30 12:00

import random

from django.db import migrations, models


def assign_organization_numbers(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    used = set(
        Organization.objects.exclude(organization_number=None).values_list(
            "organization_number", flat=True
        )
    )
    for organization in Organization.objects.filter(organization_number=None):
        number = None
        for _ in range(50):
            candidate = random.randint(100000000, 999999999)
            if candidate not in used:
                number = candidate
                used.add(candidate)
                break
        if number is None:
            raise RuntimeError("Could not allocate an organization number.")
        organization.organization_number = number
        if not organization.portal_name:
            organization.portal_name = f"store{number}"
        organization.save(update_fields=["organization_number", "portal_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='date_format',
            field=models.CharField(choices=[('dd_mmm_yyyy', 'dd MMM yyyy'), ('mm_dd_yyyy', 'MM/dd/yyyy'), ('dd_mm_yyyy', 'dd/MM/yyyy'), ('yyyy_mm_dd', 'yyyy-MM-dd')], default='dd_mmm_yyyy', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_year',
            field=models.CharField(choices=[('january_december', 'January - December'), ('april_march', 'April - March'), ('july_june', 'July - June'), ('october_september', 'October - September')], default='january_december', max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_stub_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_stub_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_stub_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_stub_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_stub_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='portal_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='update_address_in_previous_transactions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='use_payment_stub_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, choices=[('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('it_software', 'IT / Software'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('consulting', 'Consulting'), ('hospitality', 'Hospitality'), ('real_estate', 'Real Estate'), ('transportation', 'Transportation'), ('agriculture', 'Agriculture'), ('finance', 'Finance'), ('food_groceries', 'Food, Groceries & Beverages'), ('technology', 'Technology'), ('services', 'Services'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='organization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=10),
        ),
        migrations.RunPython(assign_organization_numbers, migrations.RunPython.noop),
    ]
