# Generated by Django 4.2.30 on 2026-09-07 17:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales_orders", "0001_initial"),
        ("customers", "0005_customer_accounts_receivable_customer_currency_and_more"),
        ("items", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryChallan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("challan_number", models.CharField(max_length=30)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("challan_date", models.DateField(default=datetime.date.today)),
                (
                    "challan_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("job_work", "Job Work"),
                            ("supply_on_approval", "Supply on Approval"),
                            ("supply_of_liquid_gas", "Supply of Liquid Gas"),
                            ("others", "Others"),
                        ],
                        default="job_work",
                        max_length=40,
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        blank=True,
                        choices=[("exclusive", "Exclusive"), ("inclusive", "Inclusive")],
                        default="exclusive",
                        max_length=20,
                    ),
                ),
                ("customer_notes", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "DRAFT"),
                            ("delivered", "DELIVERED"),
                            ("returned", "RETURNED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("currency", models.CharField(blank=True, default="INR", max_length=3)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_delivery_challans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_challans",
                        to="customers.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_challans",
                        to="organizations.organization",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_challans",
                        to="sales_orders.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_challans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryChallanLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=19),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("tax", models.CharField(blank=True, max_length=100)),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "delivery_challan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="delivery_challans.deliverychallan",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_challan_lines",
                        to="items.item",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_challan_lines",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="deliverychallan",
            constraint=models.UniqueConstraint(
                fields=("organization", "challan_number"),
                name="unique_org_challan_number",
            ),
        ),
    ]
